### PR TITLE
Revamped repo

### PR DESCRIPTION
**Pull request by znk**
Hello @cullophid , 
Part of my work, I needed to transpile across few modules. Here is a up-to-date of yours. If you have some comments or changes in mind to this PR, I will take time to include them as well.
Thanks for this module. It has leverage and clarified obscure parts of piece of code elegantly.

Cheers :sparkles:

### CODE REVIEW

**Comment by znk** [comment]
I opted in favour of Babili for the existing ecosystem available. But Bublé is geat IMO.

**Comment by cullophid** [comment]
im not quite sure what the point in the pr is ?

**Comment by darrylhebbes** [comment]
It a bit like a person breaks into your house, re-arranges the furniture, cleans the (already clean) dishes and then leaves...

**Comment by znk** [comment]
@cullophid i needed to include the whole module as part of vendor bundle for browser and node, so organized as such and followed conventions. will close PR

@darrylhebbes it only affects my clone, not his. git 101, bud

**Pull request closed without merging**
