### PR TITLE
First draft of docs

### PR DESCRIPTION
**Pull request by svozza**
This is a WIP but just before I do any more I want to make sure I'm on the right track. I've added type signatures to all the functions except `curry` and `compose` because I'm not sure how to represent variadic functions using Haskell style notation. Also, I wasn't sure what `search` does so I left it blank as well.

### CODE REVIEW

**Comment by cullophid** [comment]
Nice job, its a lot better that what i had :+1:

**Comment by svozza** [comment]
Cool. What does `search` do? Also, any suggestion on variation functions? The nuclear option is to disallow them completely and pass the args in as an array.

**Comment by cullophid** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/search

Is there any variadic function you think we should include ?

**Comment by svozza** [comment]
Well, the only one we have is `compose` and I'm presuming we probably want `pipe`. Other than that I don't think there are others we need.

**Pull request merged**
